language: "perl"
perl:
  - "5.20"

install:
    - cpanm swat
    - cpanm --installdeps . && perl Makefile.PL && make test && sudo make install

script: "nestd start && nestd stop && nestd restart && --host 127.0.0.1 --port 4441 && nestd status && swat ./swat && nestd stop"
