---
abstract: 'Custom Sparrow repository manager'
author:
  - 'L<Alexey Melezhik|mailto:melezhik@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.18'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sparrow-Nest
no_index:
  directory:
    - inc
    - t
requires:
  Mojolicious::Lite: 0
  Plack: 0
  Starman: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/melezhik/sparrow-nest
version: 0.0.1
